name: Npm Workflow
on:
  push:
    paths:
      - 'resources/js/*'

jobs:
  build:
    name: Npm build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run production
